version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo Before restore
      - echo Restore started on the 'date'
      - echo 'hello Good morning'
      - echo ' build run by anand'
      - dotnet restore demoapp.csproj     
  build:
    commands:
      - echo 'build started'
      - echo Start date on the 'date'
      - dotnet build demoapp.csproj
      
  post_build:
     commands:
       - dotnet publish -c Release -o ./build_output demoapp.csproj   
       -  echo 'publish in post build completed'
      
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
    
